# This is a basic workflow to help you get started with Actions

name: Scan

# Controls when the workflow will run
on:
  # Run every 10 minutes
  schedule:
    - cron: "*/10 * * * * "

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          architecture: x64
          
      
      - name: Install required libraries
        run: |
         python -m pip install requests remotezip


      - name: Collect versions and save
        run: |
         python scripts/versionscan.py
         
 
      - name: Commit and Push
        run: |
         git config --global user.name "AntiBitti[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Updated latest AbiTikku version list"
         git push

